[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snt_lib"
version = "1.0.1"
requires-python = ">=3.12"
dependencies = [
    "openhexa.sdk>=2.8.0",
    "papermill>=2.6.0",
    "pandas>=2.2.3",
    "sqlalchemy==2.0.39",
    "pyarrow>=18.1.0",
    "psycopg2-binary==2.9.10",
    "requests>=2.32.3",
    "nbclient>=0.10.2",
    "GitPython>=3.1.44",
    "geopandas>=1.0.1",
    "polars>=1.39.3",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "nbformat",
    "ruff==0.15.22",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
# Set line length (default is 88, match Black)
line-length = 120

[tool.ruff.lint]
preview = true
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "I", # isort
    "D", # pydocstyle
    "UP", # pyupgrade
    "ANN", # flake8-annotations
    "B", # bugbear
    "A", # flake8-builtins
    "COM", # flake8-commas
    "FA", # flake8-future-annotations
    "PT", # flake8-pytest-style
    "Q", # flake8-quotes
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
    "NPY", # NumPy rules
    "PD", # pandas rules
    "N", # pep8-naming
    "DOC", # pydoclint
    "PLC", # pylint convention
    "PLE", # pylint error
    "PLW", # pylint warning
    "RUF", # ruff specific rules
]

ignore = [
    "unsorted-imports", # Alphabetic order of imports 
    "undocumented-public-module", # Missing docstring in public module
    "undocumented-public-package", # Missing docstring in public package
    "undocumented-magic-method", # Missing docstring in magic method
    "undocumented-public-nested-class", # Missing docstring in public nested class
    "undocumented-public-init", # Missing docstring in __init__
    "non-imperative-mood", # First line should be in imperative mood
    "missing-blank-line-after-last-section", # Missing blank line after last section
    "incorrect-section-order", # Order of the docstring sections
    "incorrect-blank-line-before-class", # 1 blank line required before class docstring
    "multi-line-summary-second-line", # Summary on second line (incompatible with multi-line-summary-first-line)
    "if-else-block-instead-of-if-exp", # Use ternary operators
    "collapsible-if", # Use a single if statement instead of nested if statements
    "if-with-same-arms", # Combine `if` branches
    "docstring-missing-exception", # Raised exception {id} missing from docstring	
    "docstring-extraneous-exception", # Raised exception is not explicitly raised: {id}	
    "unsorted-dunder-all", # `__all__` is not sorted
    "collection-literal-concatenation", # Consider expression instead of concatenation
    "too-many-public-methods", # Too many public methods ({methods} > {max_methods})
    "too-many-return-statements", # Too many return statements ({returns} > {max_returns})
    "too-many-branches", # Too many branches ({branches} > {max_branches})
    "too-many-arguments", # Too many arguments ({arguments} > {max_arguments})
    "too-many-locals", # Too many local variables ({variables} > {max_variables})
    "too-many-statements", # Too many statements ({statements} > {max_statements})
    "too-many-boolean-expressions", # Too many Boolean expressions ({expressions} > {max_expressions})
    "too-many-nested-blocks", # Too many nested blocks ({blocks} > {max_blocks}),
    "missing-trailing-comma", # Missing trailing comma
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true
suppress-dummy-args = true
suppress-none-returning = true